// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// // client wrapper

// import NavClient from "./component/NavClient";
// import Footer from "./component/Footer";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "NextShop",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
//         <NavClient />  {/* client component */}
//         {children}
//         <Footer/>
//       </body>
//     </html>
//   );
// }





import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// client wrapper

import NavClient from "./component/NavClient";
import Footer from "./component/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "NextShop",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body 
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning={true}
      >
        <NavClient />  {/* client component */}
        {children}
        <Footer/>
      </body>
    </html>
  );
}